### PR TITLE
add section failures make us experts

### PR DESCRIPTION
**Pull request by heinritzkat**
Signed-off-by: heinritzkat <111436515+heinritzkat@users.noreply.github.com>

### CODE REVIEW

**Comment by fkr** [comment]
This was discussed and worked on in today's session. Am currently reaching out to a native speaker, to confirm wether it should be "We are convinced, that the culture we build around failures is key for an innovative environment" or "We are convinced, that the culture we build around failures is the key for an innovative environment".

In order to allow for further discussion, I'll leave the PR open as well. Please feel free to comment.

**Comment by fungi** [comment]
> Am currently reaching out to a native speaker, to confirm wether it should be "We are convinced, that the culture we build around failures is key for an innovative environment" or "We are convinced, that the culture we build around failures is the key for an innovative environment".

Both versions are grammatically correct, but have distinct meanings. The first form uses "key" as an adjective to describe the culture as important or fundamental to an innovative environment. The second form uses the noun "key" as a metaphor indicating the culture unlocks an innovative environment. Strictly speaking, "key" is a different word in each example, though both have related meanings and share the same spelling which is what makes it challenging to recommend one over the other. Given the surrounding context, I think the latter version gives a bit more flavor to the text, though I'd use "is the key to" rather than "is the key for" in that case.

Separately, the comma after "we are convinced" is unnecessary and adds an unnatural pause to the sentence.

**Comment by fkr** [comment]
thanks @fungi - especially for highlighting the difference in meaning. that is helpful.
@heinritzkat can you adjust the PR (since it comes from your fork I can't edit in the PR) to use the "is the key to" variant?

**Comment by heinritzkat** [comment]
> thanks @fungi - especially for highlighting the difference in meaning. that is helpful.
> @heinritzkat can you adjust the PR (since it comes from your fork I can't edit in the PR) to use the "is the key to" variant?

Yes I will adjust it tomorrow morning!

**Comment by fungi** [comment]
> > thanks @fungi - especially for highlighting the difference in meaning. that is helpful.
> > @heinritzkat can you adjust the PR (since it comes from your fork I can't edit in the PR) to use the "is the key to" variant?
> 
> Yes I will adjust it tomorrow morning!

For a different perspective, I brought this up with a professional editor who has experience publishing for international audiences, and her take is that both examples are troublesome but for different reasons. The problem with the first example is that the adjective "key" is far less commonly encountered than the noun, which may lead some readers of English as a second language to misjudge the sentence structure. The problem with the second example is that metaphors are not universal, and should be avoided when writing for cross-cultural audiences as they may not translate clearly. The recommendation she gave is to use the form of the first example, but replace "key" with a clearer synonym such as "important," "fundamental," or "critical."

**Comment by fkr** [comment]
heh, really good feedback. Much appreciated @fungi! We should take that into consideration @heinritzkat @cedegi

**Comment by fkr** [comment]
@heinritzkat I saw that you opened a second Pull Request (#13), I'll leave the commentary in this one.
In his second comment, @fungi added the suggestion from the person that he asked, that suggested to use a different word than key (because of the two different meanings): "The recommendation she gave is to use the form of the first example, but replace "key" with a clearer synonym such as "important," "fundamental," or "critical.""

So maybe:

> We are convinced that the culture we build around failures is fundamental for an innovative environment.

what do you think @heinritzkat? I actually find the 'fundamental' makes a very strong point.
@cedegi?

**Comment by cedegi** [comment]
sounds good for me - we can use "fundamental" here.

**Comment by fkr** [comment]
@heinritzkat can you update the PR in #13 accordingly.

**Comment by heinritzkat** [comment]
> @heinritzkat I saw that you opened a second Pull Request (#13), I'll leave the commentary in this one. In his second comment, @fungi added the suggestion from the person that he asked, that suggested to use a different word than key (because of the two different meanings): "The recommendation she gave is to use the form of the first example, but replace "key" with a clearer synonym such as "important," "fundamental," or "critical.""
> 
> So maybe:
> 
> > We are convinced that the culture we build around failures is fundamental for an innovative environment.
> 
> what do you think @heinritzkat? I actually find the 'fundamental' makes a very strong point. @cedegi?

@fkr Entschuldige die späte Anpassung, das ist wohl etwas untergegangen. Passt es so wie ich es geändert habe? :)

**Comment by fkr** [comment]
awesome. thanks @heinritzkat!

**Pull request closed without merging**
