### PR TITLE
Update Design: Add Logo and Lato Font

### PR DESCRIPTION
**Pull request by maxwolfs**
Signed-off-by: maxwolfs <mail@maxwolfs.com>

[Figma Playground for Logo Creation](https://www.figma.com/file/LgDS2uLib62mZYbuCGOR5Z/Playground?node-id=0%3A1)

* implementing Lato Font 
* implementing logo and icons for open operations manifesto

with text:
image

without:
image

### CODE REVIEW

**Comment by fkr** [comment]
Have to think about  the colors. the rest seems legit.

**Comment by fkr** [comment]
ah, I only saw the logo and claim.
I have a hard time with the 'Practice' since it always translates to 'Ueben' and not 'Praktizieren' in my head.
@itrich suggested Collaboration instead. Which I like much better than practice.

**Comment by maxwolfs** [comment]
Valid Point – I have updated the og image with `collaboration` instead of `practice`

**Comment by frosty-geek** [comment]
> Valid Point – I have updated the og image with `collaboration` instead of `practice`

Old Image is still in the Repo, rest LGTM

**Review by frosty-geek — DISMISSED** [review]

**Review by frosty-geek — APPROVED** [review]
LGTM

**Comment by garloff** [comment]
Please don't merge yet!

**Comment by maxwolfs** [comment]
## New Proposal
As discussed in last Friday's session, the logo colors might be too pale, so I have started from scratch. I have dropped the attempt to depict any descriptive meaning within the form. Therefore my new approach was to work with the acronyms (oom) and begin with a clear geometric grid layout. The logo proposal is the masked center "o" with  of the left "o" and right "m" resulting in a more modern-looking design.

#### Logo:
image

#### Construction:
Bildschirmfoto 2022-10-26 um 11 00 05

#### Share Image:
image

**Comment by frosty-geek** [comment]
I agree I personally like this logo a lot better +1

**Review by itrich — CHANGES_REQUESTED** [review]
There are still some files containing the old logo, e.g. mstiles-144x144.png and others.

**Review by itrich — APPROVED** [review]
LGTM. This really looks awesome!

**Comment by maxwolfs** [comment]
Okay, so If there is no objection by 11:00 CET tomorrow, I will merge it. :)

**Pull request merged**
