### PR TITLE
Added paragraph we are transparent about incidents

### PR DESCRIPTION
**Pull request by FriederikeZelke**
Based on the discussion from the 2022 - 09 - 30: I added the paragraph We´re transparent about our incidents

https://github.com/SovereignCloudStack/open-operations-manifesto/issues/5

Signed-off-by: FriederikeZelke <116342997+FriederikeZelke@users.noreply.github.com>

### CODE REVIEW

**Review by fkr — CHANGES_REQUESTED** [review]
Left a few comments, removed some words that are imho not needed ("Fuellwoerter").

**Comment by itrich** [comment]
We just discussed in today's working group meeting, that this paragraph contains many details that are breaking with the idea of a manifesto. We recommend to merge this paragraph with the paragraph _"We're transparent about our incidents"_ and reduce the content to a minimum. @heinritzkat will work out a proposal.

**Comment by itrich** [comment]
See https://github.com/SovereignCloudStack/open-operations-manifesto/issues/5#issuecomment-1297265790

**Comment by maxwolfs** [comment]
This PR can be closed as #29 has already been merged right?

**Comment by itrich** [comment]
Hi @FriederikeZelke,

thank you for contributing and the efforts you made concluding a paragraph on _"We're transparent about incidents"_. After reading again carefully through the whole manifesto, we decided that we should merge this paragraph with the paragraph above, _"We belive that failures makes us experts". @maxwolfs opened a second PR in which we merged both paragraphs. We can still improve with the upcoming iterations and re-use content from this PR.

Looking forward to continue working with you on this important topic!

**Pull request closed without merging**
