### PR TITLE
First draft to restructure signing and founding orgs

### PR DESCRIPTION
**Pull request by itrich**
This PR addresses #37 as discussed during the last meetings.

image

We still need to make sure
- every organization allows us to use their logo
- every contributor is fine with his/her role
- we didn't miss anybody

### CODE REVIEW

**Comment by berendt** [comment]
Does it make sense to move the logos to a subdirectory in assets? If there are many more logos later, it will be easier to keep track of them.

**Comment by itrich** [comment]
Usage of company logo:
- [ ] Cloudical
- [ ] Wavecon
- [ ] OSISM
- [ ] PlusServer
- [ ] SCS

**Review by maxwolfs — DISMISSED** [review]
lgtm

**Review by frosty-geek — APPROVED** [review]
LGTM

Use of the logo is permitted in the scope of open operations (reviewed with @Phil9219)

**Pull request merged**
